apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-template-ingress
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - pathType: Prefix
            path: /api/fastapi-template
            backend:
              service:
                name: fastapi-template
                port:
                  number: 8000
